In [1]:
import pandas as pd

In [17]:
owid = pd.read_csv('https://github.com/owid/covid-19-data/raw/master/public/data/latest/owid-covid-latest.csv', low_memory=False)
text_cols = ['location']
int_cols = ['people_vaccinated', 'people_fully_vaccinated', 'population']
cols = text_cols + int_cols

owid[int_cols] = owid[int_cols].astype('object')
owid = owid[cols]

# Get %
owid['One Dose %'] = owid['people_vaccinated']/owid['population']
owid['Both Doses %'] = owid['people_fully_vaccinated']/owid['population']
owid

,location,people_vaccinated,people_fully_vaccinated,population,One Dose %,Both Doses %
0,Afghanistan,5066540.0,4402868.0,39835428.0,0.127187,0.110526
1,Africa,276071777.0,204063406.0,1373486472.0,0.201001,0.148573
2,Albania,1275907.0,1209791.0,2872934.0,0.444113,0.421099
3,Algeria,7461932.0,6110712.0,44616626.0,0.167246,0.13696
4,Andorra,NaN,NaN,77354.0,NaN,NaN
...,...,...,...,...,...,...
227,Wallis and Futuna,NaN,NaN,11094.0,NaN,NaN
228,World,5037550545.0,4494014072.0,7874965730.0,0.639692,0.570671
229,Yemen,643501.0,404781.0,30490639.0,0.021105,0.013276
230,Zambia,2764508.0,2094075.0,18920657.0,0.146111,0.110677
231,Zimbabwe,4413298.0,3440370.0,15092171.0,0.292423,0.227957